permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]



paginate: 10
paginate_path: ":num"

baseurl: ""

title: "Yoer"
email: "iamyoer@gmail.com"
description: "..."
github_username:  "yoer"

url: "https://github.com/yoer/yoer.github.io/"
imgrepo: "https://github.com/yoer/yoer.github.io//static/img"

